program = { module } ;

module = [{ useStmt }] , { declaration } ;
useStmt = "use" , identifier , [{ "." , identifier }] , ";" ;

declaration = classDecl
            | functionDecl
            | varDecl ;
classDecl = "class" , identifier, [ typeParameters ] , [ ":" , type , { ", " type } ] , blockStmt ;
functionDecl = [( "virtual" | "override" )] , "fn" , identifier , typeParameters , parameters , [ ":" , type ] , blockStmt ;
varDecl = "let" , identifier [ ":",  type ] , "=" , expression , ";" ;
objVarDecl = identifier ":" , type , [ "=" , expression ] , ";" ;

statement = expressionStmt
          | blockStmt
          | assignmentStmt
          | returnStmt ;
expressionStmt = expression , ";" ;
blockStmt = [{ varDecl | statement }] ;
classBlody = [{ objectVarDecl | initStmt | deinitStmt | statement }] ;
assignmentStmt = expression , ( "=" | "+=" | "-=" | "*=" | "/=" ) , expressionStmt ;
initStmt = "init" , parameters , blockStmt ;
deinitStmt = "deinit" , blockStmt ;
returnStmt = "ret" , expression ;

expression = precedenceExpr ;
precedenceExpr = ? unary/binary expression with primaryExpr as values ? ;
castExpr = expression , [ "as" type ] ;
(* indexerExpr = primaryExpr , [ "[" , expression , "]" ] ; *)
dotExpr = primaryExpr ,  [ "." , dotExpr ] ;
primaryExpr = variableExpr
            | callExpr
            | groupExpr
            | newExpr
            | literal
            | ifExpr
            | listExpr
            | self
            | super ;

variableExpr = identifier ;
callExpr = modulePath , typeArguments , arguments ;
groupExpr = "(" , expression , ")" ;
newExpr = "new" , type , arguments ;
literal = bool | number | string | char ;
listExpr = "[" , expression , [ "," , expression ] , "]" ;
self = "self" ;
super = "super" , [ arguments ] ;

parameters = "(" , [ parameter , [{ "," , parameter }] ] , ")" ;
parameter = identifier , [ ":" , type ] ;
arguments = "(" , [ expression , [{ "," , expression }] ] , ")" ;
typeArguments = "[" , type , [{ "," , type }] , "]" ;
typeParameters = "[" , identifier , [{ "," , identifier }] , "]" ;
modulePath = identifier , [{ "->" , identifier }] ;
type = modulePath , [ typeArguments ] ;

bool = "true" | "false" ;
number = /[0-9]+(\.[0-9]+)/ ;
string = '"' , ? anything ? , '"' ;
char = "'" , ? any utf-8 character ? , '"' ; (* utf-8? *)
identifier = /[A-z_]+/ ;